#!/usr/bin/env bash
# Install pre-commit hook that auto-regenerates the AST map on .ts changes.
# Per-Beast install — git hooks are not versioned in .git/hooks/.
# Idempotent: safe to re-run.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
# Use git-path so this works in both standard clones and worktrees off bare clones.
# In a worktree, .git is a pointer file not a directory, so direct .git/hooks/ fails.
HOOK_PATH="$(git rev-parse --git-path hooks/pre-commit)"
HOOK_DIR="$(dirname "$HOOK_PATH")"
mkdir -p "$HOOK_DIR"

cat > "$HOOK_PATH" <<'HOOK_EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-ast-hook.sh — Denbook AST Map pre-commit hook.
# Regenerates ast-map.{json,md} when any src/**/*.ts file is staged.
# Adds regenerated outputs to the in-flight commit so the AST stays synced with code.

set -euo pipefail

# Check if any staged file is under src/ and matches .ts
ts_staged=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '^src/.*\.ts$' || true)

if [ -z "$ts_staged" ]; then
  exit 0
fi

# Regenerate AST map
if [ -f scripts/ast-map.ts ]; then
  bun scripts/ast-map.ts > /dev/null 2>&1
  # Stage the regenerated outputs if they changed
  if [ -f ast-map.json ] && [ -f ast-map.md ]; then
    git add ast-map.json ast-map.md
  fi
fi

exit 0
HOOK_EOF

chmod +x "$HOOK_PATH"

echo "✓ Installed AST pre-commit hook at $HOOK_PATH"
echo ""
echo "Hook regenerates ast-map.{json,md} when any src/**/*.ts is staged"
echo "+ adds outputs to the in-flight commit."
